### ISSUE TITLE
Business process implementation (proposed XPDL)

### ISSUE THREAD

**Issue by bmrki** [Esgariot/DigitalDocuments_Bookstore#13]
implement project graph into xpdl

**Comment by syki1** [comment]
![xpdl3](https://user-images.githubusercontent.com/26256204/47288076-c514a080-d5f4-11e8-97da-97427d49d78c.jpg)

**Comment by syki1** [comment]
[Proces biznesowy Dokumenty Cyfrowe.pdf](https://github.com/Esgariot/DigitalDocuments_Bookstore/files/2500966/Proces.biznesowy.Dokumenty.Cyfrowe.pdf)

**Comment by syki1** [comment]
[XPDL.txt](https://github.com/Esgariot/DigitalDocuments_Bookstore/files/2500973/XPDL.txt)

**Comment by Esgariot** [comment]
hopefully this will __auto-resolve__ based on comments in pull requests #21  and #22
