### ISSUE TITLE
email from client persistency

### ISSUE THREAD

**Issue by bmrki** [Esgariot/DigitalDocuments_Bookstore#16]
figure out a way to store and display pending emails from clients - ask smtp server for mailbox, filter out ones without x-metadata or have some sort of persistency storage (sqlite or text file) that holds not-yet-accepted emails

**Comment by Ernestynian** [comment]
![example](https://user-images.githubusercontent.com/9627602/47320681-6ed64a80-d652-11e8-84c6-06f14e865fd6.PNG)
Image just in case noone would be able to show it live (i certainly won't).
